import type { NextPage } from "next";
import Head from "next/head";
import Card from "../components/Card";
import InfoCard from "../components/InfoCard";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>The Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <InfoCard />
    </div>
  );
};

export default Home;
